import { Request, Response, Router } from 'express';
import swaggerUi from 'swagger-ui-express';

const apiRouter: Router = Router();

// Manually add routes that were not generated by TSOA here

apiRouter.use('/docs', swaggerUi.serve, async (_req: Request, res: Response) => {
    return res.send(swaggerUi.generateHTML(await import('./swagger.json')));
});

export default apiRouter;
